language: rust
cache: cargo

rust:
  - nightly

matrix:
  include:
    - env: TARGET=x86_64-unknown-linux-gnu
      os: linux

install:
  - rustup self update
  - rustup target add $TARGET; true

script:
  - cargo build --target $TARGET --verbose
  - cargo build --target $TARGET --verbose --examples
